name: Test VFB Terms Generation

on:
  push:
    paths:
      - 'vfbterms.py'
      - '.github/workflows/test_vfbterms.yml'
  pull_request:
    paths:
      - 'vfbterms.py'
      - '.github/workflows/test_vfbterms.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vfb-connect pandas

      - name: Run medulla test
        run: |
          python3 vfbterms.py

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            FBbt_00003748_v*.md
          retention-days: 7 